name: Create Release Branch

run-name: Create Release Branch ${{ github.event.inputs.new_tag }}

on:
  workflow_dispatch:
    inputs:
      base_tag:
        description: 'Base tag (must start with v)'
        required: true
        default: 'v'
      new_tag:
        description: 'New tag (must start with v)'
        required: true
        default: 'v'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: refs/tags/${{ github.event.inputs.base_tag }}

      - name: Create release branch
        env:
          BRANCH: release/${{ github.event.inputs.new_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH
          git push https://x-access-token:${{steps.generate_token.outputs.token}}@github.com/${{ github.repository }}.git $BRANCH:$BRANCH
